### PR TITLE
to keep instruction on embedding youtube videos

### PR DESCRIPTION
**Pull request by vladdsm**
Hi, I am using this template for my static blog. Keeping this instruction to embed youtube videos could be useful for others

### CODE REVIEW

**Comment by arkadianriver** [comment]
Excellent idea, Vlad, to include not only this, but other nifty include templates to make it easy for bloggers, similar to shortcodes in Hugo.

I will close and not merge this particular pull request, though, because I'd rather reserve the Readme for installation and getting started info only. But, I will make a document with this and other templates with the rest of the documentation in the future posts area.

Also, I might have to play with the CSS to make these iframes responsive, or (depending on most audience's browser capabilities) use HTML5 `<video/>` tags instead of iframes. If you look at your videos on mobile, they cut off to the right. The _good news_ is that if it ends up better to use the video tag, you used an include, so the change need only be made in one place! 😸 Again, you have a great idea here. Thanks!

**Comment by arkadianriver** [comment]
Do you mind if I give you credit for the idea on the credits page and link to one of the videos on your youtube series as an example?

**Comment by vzhomeexperiments** [comment]
Hi Gary, 
You are totally correct: size of the video will not be dynamically resized on mobile applications. I found personally no issue with that because most people would have youtube app installed on their smartphones so video will be then resized once they will watch...
By the way, the idea of including youtube videos without plugins is not mine. I just used the method and wanted to suggest improvement for the site template (which I got from your repository)... original source of idea is from [here](https://adam.garrett-harris.com/how-to-easily-embed-youtube-videos-in-jekyll-sites-without-a-plugin/)
Nevertheless if you need an example of the website with video 'included' this way: [here it is](https://vladdsm.github.io/myblog_attempt/topics/lazy%20trading/)

**Comment by arkadianriver** [comment]
Implemented in latest push with instructions in restructured user guide. I included Twitter links for both you and Michael in credits page, but your videos were too deep for use as example, I think :) Used short funny vids instead, from embedresponsively. Credited in CSS comments.  If you load main.scss and post_youtube.html include, you'll get the responsive link

**Pull request closed without merging**
